import test from 'node:test';
import assert from 'node:assert/strict';
import {claim,accept,smokePassed} from '../scripts/run_vercel_turns.mjs';
function setup(){const plan={smoke_ids:['s1','s2'],clip_ids:['s1','s2','f1'],configs:{a:{provider:'shared',turn_finalization_class:'controlled'},b:{provider:'shared',turn_finalization_class:'controlled'}},max_workers:10,max_workers_per_model:32,durations:{s1:1,s2:2,f1:3}};const state={models:Object.fromEntries(['a','b'].map(name=>[name,{name,rows:{},active:{},ceiling:1,peak:0}])),providers:{shared:{limit:1,cooldown:0,external:0,reductions:[]}}};return {plan,state};}
const result=id=>({clip_id:id,attempt:1,valid:true,turn_timing:{ttft_ms:400,ttfs_ms:200}});
test('shared provider cap and smoke gating cover parallel shards',()=>{const {plan,state}=setup();assert.deepEqual(claim(plan,state,'a','w1'),['s1']);assert.equal(claim(plan,state,'b','w2'),null);accept(plan,state,'a','w1',[result('s1')]);assert.deepEqual(claim(plan,state,'a','w1'),['s2']);accept(plan,state,'a','w1',[result('s2')]);assert(smokePassed(plan,state.models.a));assert.deepEqual(claim(plan,state,'a','w1'),['f1']);});
test('failed smoke blocks full turns and never retries a recorded attempt',()=>{const {plan,state}=setup();claim(plan,state,'a','w1');accept(plan,state,'a','w1',[{...result('s1'),valid:false}]);assert.equal(claim(plan,state,'a','w1'),null);assert.equal(state.models.a.blocked,'smoke_failed');});
test('external sessions reserve shared capacity',()=>{const {plan,state}=setup();state.providers.shared.external=1;assert.equal(claim(plan,state,'a','w1'),null);});
test('duplicate receipts fail closed',()=>{const {plan,state}=setup();claim(plan,state,'a','w1');assert.throws(()=>accept(plan,state,'a','w1',[result('s1'),result('s1')]),/Duplicate/);});

test('explicit empty completed smoke allows remaining turns without retry or zero latency',()=>{const {plan,state}=setup();plan.smoke_policy='completed-empty-allowed-v1';const empty={...result('s1'),turn_timing:{ttft_ms:null,ttfs_ms:null,ttft_status:'no_text',ttfs_status:'no_final_text'}};state.models.a.rows={s1:empty,s2:result('s2')};assert(smokePassed(plan,state.models.a));assert.deepEqual(claim(plan,state,'a','w1'),['f1']);empty.valid=false;assert(!smokePassed(plan,state.models.a));});

test('AssemblyAI reserves all five admissions before setup and blocks the sixth',()=>{const {plan,state}=setup();plan.configs.a.provider='assemblyai';plan.assemblyai_new_sessions_per_minute=5;plan.clip_ids=['s1','s2','f1','f2','f3','f4','f5','f6'];state.models.a.rows={s1:result('s1'),s2:result('s2')};state.models.a.ceiling=20;state.providers.assemblyai={limit:20,cooldown:0,external:0,started:[],pendingStarts:0};for(let i=0;i<5;i++)assert(claim(plan,state,'a','w'+i,100000));assert.equal(state.providers.assemblyai.pendingStarts,5);assert.equal(claim(plan,state,'a','w5',100000),null);state.providers.assemblyai.pendingStarts--;state.providers.assemblyai.started.push(100100);assert.equal(claim(plan,state,'a','w5',100200),null);assert(claim(plan,state,'a','w5',165101));});
test('recovery plan uses one clip per batch and waits before the next session',()=>{const {plan,state}=setup();plan.single_clip_batches=true;plan.minimum_batch_interval_ms=65000;plan.clip_ids.push('f2');state.models.a.rows={s1:result('s1'),s2:result('s2')};assert.deepEqual(claim(plan,state,'a','w1'),['f1']);accept(plan,state,'a','w1',[result('f1')]);assert.equal(claim(plan,state,'a','w1'),null);assert.deepEqual(claim(plan,state,'a','w1',Date.now()+65001),['f2']);});
