"""The agent bench's own columns: what only the reference agent could record.

A scored call has two witnesses. The platform that placed it holds the
recording and the transcript, and everything read from those -- whether the
task was done, whether the line worked, how long the caller waited -- comes
from there, through the same collation as every other row on the board. The
agent holds what never reaches a recording: which build answered, how it was
configured, what the call consumed, what each tool was asked and answered, and
whether the call was delivered as a call. This module turns the second set
into the columns a board row carries beside the first.

Input is one JSON object per run, as exported from the platform:

    {"run_id": ..., "scenario_id": ..., "custom_metadata": {...the agent's record...}}

``custom_metadata`` is exactly what the reference agent stamped on the run.
Nothing else is read, so the output is a function of the export and can be
regenerated by anyone holding it.

Rules, stated once:

* **One build per row.** A row whose runs carry more than one agent commit is
  refused: a board cell describes one build, and a mixture describes none.
* **One suite per row.** Each agent definition is its own prompt, tools and
  scenarios, so a provider gets one row per definition, and nothing is
  combined across them.
* **Cost is a ratio of totals.** Per minute is total priced dollars over total
  priced call minutes, so long calls weigh as much as they cost. A cost is
  publishable only when every run in the row was priced from verified rates;
  otherwise the row says how many were, and why the rest were not.
* **Who closed the call is counted.** A call the agent said goodbye to and
  left open is closed by the harness, the same way on every row; those runs
  are tallied under ``closed_by`` so the model's miss stays visible.
* **A flagged run is counted, not dropped.** Integrity checks name runs that
  need looking at before they are scored; the tally is published beside the
  score so an exclusion decided later is visible as one.
* **Latency is not a column here.** The agent's own timings are
  detector-derived and measured at the agent, not at the caller's ear, so the
  board's latency is the platform's, read from the recording. Every turn the
  agent timed is still written out, one line each, with when in the call the
  caller stopped, so the two can be lined up turn by turn later.

    python -m agent.report runs.jsonl [--out harness-columns.json] [--turns agent-turns.jsonl]
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from collections.abc import Iterable, Sequence
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from pricing.cost import load_table, price_call

# The fields that name a configuration. A row that differs in one of these from
# another row is a different configuration, and the board has to be able to say so.
CONFIGURATION_FIELDS = (
    "s2s_provider", "s2s_model", "s2s_voice", "stack", "turn_source", "pipeline_sample_rate",
    "agent_definition", "system_prompt_sha256", "first_message_sha256", "tools",
    "pipecat_version", "cekura_version", "hangup_backstop", "shared_rules_sha256",
)
# What a provider row discloses beyond the common fields, by name. Read from the
# record rather than listed here, because the agent decides what each row owes.
COMMON_FIELDS = set(CONFIGURATION_FIELDS) | {
    "bench", "agent_commit", "config_source", "config", "worker_instance", "worker_call",
    "cekura_mode", "divergences", "tool_calls", "tool_call_count", "tool_calls_matched",
    "tool_calls_cancelled", "usage", "timing", "integrity", "cekura_agent_id",
}
CALL_CONTROL = {"end_call", "transfer_call"}


class ReportError(ValueError):
    """The export cannot be turned into a row without misdescribing it."""


def load_runs(paths: Iterable[str | Path]) -> list[dict[str, Any]]:
    runs = []
    for path in paths:
        for number, line in enumerate(Path(path).read_text().splitlines(), 1):
            if not line.strip():
                continue
            run = json.loads(line)
            if not isinstance(run.get("custom_metadata"), dict):
                raise ReportError(f"{path}:{number}: run {run.get('run_id')} carries no agent record")
            runs.append(run)
    return runs


def _single(values: Sequence[Any], what: str, row: str) -> Any:
    distinct = sorted({json.dumps(v, sort_keys=True) for v in values})
    if len(distinct) != 1:
        raise ReportError(f"{row}: runs disagree on {what} ({len(distinct)} values); one row is one build")
    return json.loads(distinct[0])


def configuration(records: Sequence[dict[str, Any]], row: str) -> dict[str, Any]:
    config = {field: _single([r.get(field) for r in records], field, row) for field in CONFIGURATION_FIELDS}
    config["divergences"] = _single([r.get("divergences") for r in records], "divergences", row)
    disclosed = sorted({key for r in records for key in r} - COMMON_FIELDS)
    config["disclosures"] = {key: _single([r.get(key) for r in records], key, row) for key in disclosed}
    return config


def cost(records: Sequence[dict[str, Any]], row: str, table: dict[str, Any]) -> dict[str, Any]:
    priced, refused = [], Counter()
    verified, basis, unmetered = True, None, ()
    for record in records:
        usage = record.get("usage") or {}
        price = price_call(row, usage, table)
        basis, unmetered = price.basis, price.unmetered
        verified = verified and price.verified
        if price.usd is None:
            refused[price.reason] += 1
        else:
            priced.append((price, usage.get("call_seconds") or 0))

    minutes = sum(seconds for _, seconds in priced) / 60
    total = sum(price.usd for price, _ in priced)
    lines = defaultdict(float)
    for price, _ in priced:
        for name, usd in price.lines.items():
            lines[name] += usd
    return {
        "per_minute_usd": round(total / minutes, 4) if minutes else None,
        "per_call_usd": round(total / len(priced), 4) if priced else None,
        "per_minute_by_component_usd": {n: round(v / minutes, 4) for n, v in lines.items()} if minutes else {},
        "priced_runs": len(priced),
        "unpriced_runs": dict(refused),
        "basis": basis,
        "verified": verified,
        "publishable": verified and bool(priced) and not refused,
        "unmetered": list(unmetered),
        "excludes": "transport, hosting and the platform that placed the call; the same for every row",
    }


def _spread(values: Sequence[float]) -> dict[str, Any] | None:
    if not values:
        return None
    ordered = sorted(values)
    return {"count": len(ordered), "p50": ordered[len(ordered) // 2],
            "p90": ordered[min(len(ordered) - 1, int(0.9 * len(ordered)))], "max": ordered[-1]}


def integrity(records: Sequence[dict[str, Any]]) -> dict[str, Any]:
    flagged = Counter()
    closed_by = Counter()
    clean = 0
    missing = 0
    tails = []
    for record in records:
        checks = (record.get("integrity") or {}).get("checks")
        if checks is None:
            missing += 1
        elif checks == ["ok"]:
            clean += 1
        else:
            flagged.update(checks)
        closed_by[(record.get("integrity") or {}).get("closed_by") or "caller_or_timeout"] += 1
        tail = (record.get("integrity") or {}).get("hangup_tail_ms")
        if tail is not None:
            tails.append(tail)
    return {"ok_runs": clean, "flagged_runs": len(records) - clean - missing, "flags": dict(flagged),
            "runs_without_checks": missing, "hangup_tail_ms": _spread(tails), "closed_by": dict(closed_by)}


def tools(records: Sequence[dict[str, Any]]) -> dict[str, Any]:
    resolutions = Counter()
    calls = cancelled = runs_with_repeats = runs_without_close = 0
    for record in records:
        trace = record.get("tool_calls") or []
        seen = Counter()
        closed = False
        for call in trace:
            calls += 1
            if call.get("cancelled"):
                cancelled += 1
                continue
            if call.get("name") in CALL_CONTROL:
                closed = True
                continue
            resolutions[call.get("resolution", "none")] += 1
            seen[(call.get("name"), json.dumps(call.get("arguments"), sort_keys=True))] += 1
        runs_with_repeats += any(count > 1 for count in seen.values())
        runs_without_close += not closed
    return {"calls": calls, "cancelled": cancelled, "resolutions": dict(resolutions),
            "runs_with_a_repeated_call": runs_with_repeats, "runs_not_closed_by_the_agent": runs_without_close}


def summarize_row(row: str, suite: str, runs: Sequence[dict[str, Any]], table: dict[str, Any]) -> dict[str, Any]:
    records = [run["custom_metadata"] for run in runs]
    label = f"{row} ({suite})"
    commit = _single([r.get("agent_commit") for r in records], "agent_commit", label)
    return {
        "row": row,
        "suite": suite,
        "runs": len(runs),
        "scenarios": len({run.get("scenario_id") for run in runs}),
        "agent_commit": commit,
        "configuration": configuration(records, label),
        "cost": cost(records, row, table),
        "integrity": integrity(records),
        "tools": tools(records),
    }


def summarize(runs: Sequence[dict[str, Any]], table: dict[str, Any] | None = None) -> dict[str, Any]:
    table = table if table is not None else load_table()
    by_row: dict[tuple[str, str], list[dict[str, Any]]] = defaultdict(list)
    for run in runs:
        by_row[_row(run["custom_metadata"]), _suite(run["custom_metadata"])].append(run)
    return {
        "schema": "agent_bench_harness_columns_v1",
        "price_table": {"schema": table.get("schema"), "note": table.get("note")},
        "rows": [summarize_row(row, suite, rows, table) for (row, suite), rows in sorted(by_row.items())],
    }


def _row(record: dict[str, Any]) -> str:
    return record.get("config") or record.get("s2s_provider") or "unknown"


def _suite(record: dict[str, Any]) -> str:
    return record.get("agent_definition") or "unknown"


def turns(runs: Sequence[dict[str, Any]]) -> list[dict[str, Any]]:
    """Every turn the agent timed, one row each, measured at the agent."""
    rows = []
    for run in runs:
        record = run["custom_metadata"]
        timing = record.get("timing") or {}
        for kind in ("reply", "endpointing"):
            for turn in (timing.get(kind) or {}).get("turns") or ():
                rows.append({
                    "row": _row(record), "suite": _suite(record),
                    "run_id": run.get("run_id"), "scenario_id": run.get("scenario_id"),
                    "measure": f"agent_{kind}_ms", "caller_stopped_at_s": turn.get("caller_stopped_at_s"),
                    "ms": turn.get("ms"),
                })
    return rows


def main(argv: Sequence[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("exports", nargs="+", help="JSONL files, one run per line")
    parser.add_argument("--out", help="write here instead of stdout")
    parser.add_argument("--turns", help="also write every timed turn here, one JSON object per line")
    args = parser.parse_args(argv)
    try:
        runs = load_runs(args.exports)
        report = summarize(runs)
    except ReportError as exc:
        print(f"refused: {exc}", file=sys.stderr)
        return 2
    if args.turns:
        Path(args.turns).write_text("".join(json.dumps(row) + "\n" for row in turns(runs)))
    text = json.dumps(report, indent=2) + "\n"
    if args.out:
        Path(args.out).write_text(text)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
